#include <iostream>
#include "Lexer.hpp"
#include "Parser.hpp"
#include "CodeGen.hpp"

int main() {
    std::cout << "Hello, RunQ!" << std::endl;

    // ### FLAGS (for debug) ### //
    bool generateCompiledFiles = true; // if output.o, output.s and output will be generated by codegen
    // ######################### //

    std::string source = "fn main( ) : i32 { \n"
                         "  \n"
                         "  let i32 x = 12;\n"
                         "  let i8 y = 128;\n"
                         "  let f64 pi = 3.141592;\n"
                         "  let char letter = 'q';\n"
                         "  let bool isSomething = true;\n"
                         "  \n"
                         // "  if false { \n"
                         "      return x + 27 + 6;\n" // 45 // exit codes on linux are only 0 - 255
                         // "  }\n"
                         // "  else { \n"
                         // "      return 27 + x + x;\n" // 51
                         // "  }\n"
                         "} ";

    std::cout << "Using test source (RunQ project is in active development) ->\n" << source << "\n\nLexer out ->"<< std::endl;

    Lexer lexer(source);

    bool isAtEnd = false;
    while (!isAtEnd) {
        Token token = lexer.nextToken();
        std::cout << token << std::endl;
        if (token.type == TokenType::EndOfFile) {
            isAtEnd = true;
        }
    }

    std::cout << "\n\nParser out ->" << std::endl;

    Lexer lexer2(source);
    Parser parser(lexer2);

    parser.parse();
    parser.ast.print();

    std::cout << "\n\nLLVM out -> \n" << std::endl;

    CodeGen codegen;
    codegen.compile(parser.ast, generateCompiledFiles);

    return 0;
}