#include <iostream>
#include "Lexer.hpp"
#include "Parser.hpp"
#include "CodeGen.hpp"

#include <fstream>
#include <sstream>

std::string readFile(const std::string& path) {
    std::ifstream file(path);
    std::stringstream buffer;
    buffer << file.rdbuf();
    return buffer.str();
}

int main() {
    std::cout << "Hello, RunQ!" << std::endl;

    // ### FLAGS (for debug) ### //
    bool generateCompiledFiles = true; // if output.o, output.s and output will be generated by codegen
    // ######################### //

    std::string source = readFile("../Main.runq");

    std::cout << "Source ->\n" << source << "\n\nLexer out ->"<< std::endl;

    Lexer lexer(source);

    bool isAtEnd = false;
    while (!isAtEnd) {
        Token token = lexer.nextToken();
        std::cout << token << std::endl;
        if (token.type == TokenType::EndOfFile) {
            isAtEnd = true;
        }
    }

    std::cout << "\n\nParser out ->" << std::endl;

    Lexer lexer2(source);
    Parser parser(lexer2);

    parser.parse();
    parser.ast.print();

    std::cout << "\n\nLLVM out -> \n" << std::endl;

    CodeGen codegen;
    codegen.compile(parser.ast, generateCompiledFiles);

    return 0;
}